### PR TITLE
Fix/1068

### LINKED ISSUE #1068: [Bug] Empty aliases are stored

### PR DESCRIPTION
**Pull request by E15067**
Fixes #1068 

~~Adds form validation for newly created and existing actors.~~

The plugins where tested with the following plugin:
```js
module.exports = ({ $log }) => {
  $log('DEBUG: Trying to add an empty alias')
  return {
    aliases: ['    ', '   ', 'A Valid Alias']
  }
}
```

Configuration of the plugin:
```json
    "events": {
      "actorCreated": ["emptyAlias"],
      "actorCustom": ["emptyAlias"],
    },
    "register": {
      "emptyAlias": {
        "path": "./emptyAlias.js"
      }
    }
```

### CODE REVIEW

File: src/graphql/mutations/actor.ts [hunk 1]
```diff
@@ -110,7 +112,8 @@ export default {
         }
 
         if (Array.isArray(opts.aliases)) {
-          actor.aliases = [...new Set(opts.aliases)];
+          const aliases = opts.aliases.filter((alias) => alias && !!alias.trim());
+          actor.aliases = [...new Set(aliases)];
```
Comment (shantelwells) [inline src/graphql/mutations/actor.ts:116]: Y

File: src/graphql/mutations/actor.ts [hunk 2]
```diff
@@ -110,7 +112,8 @@ export default {
...
         }
 
         if (Array.isArray(opts.labels)) {
```
Comment (shantelwells) [inline src/graphql/mutations/actor.ts:116]: Hey

File: app/src/views/Actors.vue [hunk 3]
```diff
@@ -485,6 +486,7 @@ export default class ActorList extends mixins(DrawerMixin) {
         },
       })
         .then((res) => {
+          actorModule.setAliases(res.data.updateActors[0].aliases)
```
Comment (leadwolf) [inline app/src/views/Actors.vue:489]: When creating actors, there is not need to update the current actor's aliases, since we are not viewing any actor

File: src/graphql/mutations/actor.ts [hunk 4]
```diff
@@ -110,7 +112,8 @@ export default {
         }
 
         if (Array.isArray(opts.aliases)) {
```
Comment (leadwolf) [inline src/graphql/mutations/actor.ts:114]: You can remove the whole `if` block, just keep `actor.aliases =  [...new Set(aliases)];` and there is no need to create another `aliases` array, since you already did it above

**Review by leadwolf — CHANGES_REQUESTED** [review]

**Comment by leadwolf** [comment]
You cannot add aliases in the web ui when creating an actor, but we should filter the aliases there as well (never know if the ui will change, or how other clients will use the api).
I suggest also applying the fixes to studio aliases and label aliases

File: app/src/views/Actors.vue (hunk 3 above)
Comment (E15067) [reply app/src/views/Actors.vue:489]: Should be resolved now.

File: src/graphql/mutations/actor.ts [hunk 5]
```diff
@@ -109,9 +111,7 @@ export default {
           actor.name = opts.name.trim();
         }
 
-        if (Array.isArray(opts.aliases)) {
-          actor.aliases = [...new Set(opts.aliases)];
-        }
+        actor.aliases = [...new Set(filterInvalidAliases(opts.aliases || []))];
```
Comment (leadwolf) [inline src/graphql/mutations/actor.ts:114]: just move the new Set stuff to the first declaration, and then just do actor.aliases = aliases

**Review by leadwolf — APPROVED** [review]
@boi123212321 think it requires tests?

File: src/graphql/mutations/actor.ts (hunk 5 above)
Comment (boi123212321) [inline src/graphql/mutations/actor.ts:114]: I think this is wrong
If opts.aliases is undefined, it will use a blank array, so if you do a partial update, it will always clear the aliases. Thar's why everything is inside if blocks

File: src/graphql/mutations/studio.ts [hunk 6]
```diff
@@ -105,9 +105,7 @@ export default {
           studio.name = opts.name.trim();
         }
 
-        if (Array.isArray(opts.aliases)) {
-          studio.aliases = [...new Set(opts.aliases)];
-        }
+        studio.aliases = [...new Set(filterInvalidAliases(opts.aliases || []))];
```
Comment (boi123212321) [inline src/graphql/mutations/studio.ts:108]: Same as actor update

File: src/utils/misc.ts [hunk 7]
```diff
@@ -269,3 +269,7 @@ export function isArrayEq<
     (oldItem) => !!target.find((newItem) => sourceKey(oldItem) === targetKey(newItem))
   );
 }
+
+export function filterInvalidAliases(aliases: string[]): string[] {
+  return aliases.filter((alias) => alias && !!alias.trim());
```
Comment (boi123212321) [inline src/utils/misc.ts:274]: Callback can be be shortened to `alias => !!alias.trim()` because we know alias is always a string

**Comment by boi123212321** [comment]
> @boi123212321 think it requires tests?

Looks like it is covered by some tests, but at least separate tests for filterInvalidAliases could be useful

File: src/graphql/mutations/actor.ts (hunk 5 above)
Comment (leadwolf) [reply src/graphql/mutations/actor.ts:114]: Right, that's an oversight from me

**Review by boi123212321 — APPROVED** [review]

**Review by leadwolf — APPROVED** [review]
