### PR TITLE
Fix: could not delete movie

### LINKED ISSUE #1332: [Bug] It seems movie_scenes is not cleaned up when movie is deleted.
It seems that movie_scenes.db is not cleaned up when a movie is deleted.

Re-indexing will also not make the issue go away.

### LINKED ISSUE #1333: [Bug] Deleting a movie does not work
When clicking Delete, it stays on that screen and seemingly doesn't complete.

### PR DESCRIPTION
**Pull request by leadwolf**
- Closes #1333
- Closes #1332

### CODE REVIEW

File: src/search/movie.ts [hunk 1]
```diff
@@ -78,7 +78,7 @@ async function addMovieSearchDocs(docs: IMovieSearchDoc[]): Promise<void> {
 
 export async function removeMovie(movieId: string): Promise<void> {
   await getClient().delete({
-    index: indexMap.images,
+    index: indexMap.movies,
     id: movieId,
     type: "_doc",
```
Comment (boi123212321) [inline src/search/movie.ts:83]: Setting refresh: true here...

File: test/graphql/mutations/movie.spec.ts [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+          // TEST
+
+          const removeRes = await movieMutations.removeMovies(null, { ids: [movie._id] });
+
+          // RESULT
+
+          expect(removeRes).to.be.true;
+
+          // Wait for index update to take effect
+          await new Promise((resolve) => setTimeout(resolve, 2 * 1000));
```
Comment (boi123212321) [inline test/graphql/mutations/movie.spec.ts:48]: ...should make this await obsolete
