### PR TITLE
Fix: preview would show two images at once ; show studio, movie name fallback in details page

### LINKED ISSUE #1377: [Bug] Preview hover shows two images at once
> I noticed some incorrect extract from the combined preview image, leading to mixup of two images
image

> Video dimensions 960x544

> the preview is 160000x90, but VideoPlayer assumes 91px height from the scene's aspect ratio (Math.round)

> the size is set to "160x?" in ffmpeg
which makes the height 90.6666, so that's where the drift comes from

### PR DESCRIPTION
**Pull request by leadwolf**
- Close #1377
- Scene Details: add studio name fallback when missing logo

### CODE REVIEW

**Comment by boi123212321** [comment]
This will only fix new preview right?
The image dimensions could be retroactively stored when fetching the image's dimensions from the graphql resolver

File: app/src/views/SceneDetails.vue [hunk 1]
```diff
@@ -71,7 +77,8 @@
       <div class="mt-2 d-flex">
         <v-spacer></v-spacer>
         <router-link v-if="currentScene.studio" :to="`/studio/${currentScene.studio._id}`">
-          <v-img contain v-ripple max-width="200px" :src="studioLogo"></v-img>
+          <v-img v-if="studioLogo" contain v-ripple max-width="200px" :src="studioLogo"></v-img>
+          <span v-else>{{ currentScene.studio.name }}</span>
```
Comment (boi123212321) [inline app/src/views/SceneDetails.vue:81]: The fallback should be in MovieDetails.vue as well

**Review by boi123212321 — APPROVED** [review]
