### PR TITLE
fix #600

### LINKED ISSUE #600: [Bug] Adding actor via plugin doesn't generate other scenes
When a scene plugin creates an actor and it triggers an actor plugin then the automatic addition of other filenames/scenes with that actor doesn't trigger and only that 1 scene is added under the actor/actress.

**To Reproduce**
Reach out to tibblist for the modified ThePromisedScene plugin or once it is updated on github at https://github.com/Ch00nassid/Vault-plugins/blob/master/ThePromisedScene.js

**Expected behavior**
Same search process as manually adding an actress where the app searches through all files for any file that contains this actress to be added as a scene with this actress.

Also of note is that this is during the first run through of scenes so some scenes/files that may include the actor may not be processee yet so might need to wait for processing to finish then check for all scenes/files with the actor.

### PR DESCRIPTION
**Pull request by boi123212321**

### CODE REVIEW

File: src/types/actor.ts [hunk 1]
```diff
@@ -139,4 +143,27 @@ export default class Actor {
...
+          const sceneLabels = (await Scene.getLabels(scene)).map((l) => l._id);
+          await Scene.setLabels(scene, sceneLabels.concat(actorLabels));
+          logger.log(`Applied actor labels of new actor to ${scene._id}`);
+        }
+        await Scene.setActors(
+          scene,
+          (await Scene.getActors(scene)).map((l) => l._id).concat(actor._id)
+        );
+        try {
+          await updateScenes([scene]);
```
Comment (leadwolf) [inline src/types/actor.ts:161]: I wonder if it would be more efficient to collect the modified scenes, to be able to do a single updateScenes call at the end. But I guess it only matters when updating 1000s at a time ?

**Review by leadwolf — APPROVED** [review]

File: src/types/actor.ts (hunk 1 above)
Comment (boi123212321) [reply src/types/actor.ts:161]: More time efficient, less space efficient I'd say
But I think it's fine considering no actor ever has more than 2000 scenes or whatever (I hope)
